[build]
# Optimize build concurrency
jobs = 4

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:4194304"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "-C", "link-arg=-undefined", "link-arg=dynamic_lookup"]
